# Azure DevOps YAML pipeline for deploying an Azure Function app with private endpoint enabled
 
trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest
 
variables:
  # Azure Function app settings
  functionName: "test-private-endpoint-ema"
  resourceGroupName: "DefaultResourceGroup-WEU"
   
  # Azure Storage account settings
  storageAccountName: "emasplashapp"
  storageAccountKey: "bMWohgvScWZPEh3pOTYKC886UpHW1q0PUqKYmkD7AmDTEVb/4L1X93hpD3Eq3t3xYhjGTugZW91R+AStC8e3ww=="
  containerName: "app"
  zipFileName: "test-endpoint-v22.zip"
   
  # Deployment package settings
  sourceDirectory: "$(System.DefaultWorkingDirectory)"
  zipFile: "$(System.DefaultWorkingDirectory)/test-endpoint-v22.zip"
   
steps:
- task: ArchiveFiles@2
  displayName: 'Build Deployment Package'
  inputs:
    rootFolderOrFile: '$(sourceDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(zipFile)'

- task: AzureCLI@2
  inputs:
      azureSubscription: 'Ema sub (8a01c013-32ee-4251-b39b-75536d8edf96)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        agent_ip=$(curl -s http://ipinfo.io/ip)
        echo $agent_ip
        az storage account network-rule add --resource-group '$(resourceGroupName)' --account-name '$(storageAccountName)' --ip-address $agent_ip                
- powershell: |
    Start-Sleep -Seconds 60
  displayName: 'Wait for rule'   

- task: AzureCLI@2
  inputs:
          azureSubscription: 'Ema sub (8a01c013-32ee-4251-b39b-75536d8edf96)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            agent_ip=$(curl -s http://ipinfo.io/ip)
            echo $agent_ip
            az storage blob upload --account-name '$(storageAccountName)' --account-key '$(storageAccountKey)' --container-name 'app' --file '$(zipFile)' --name '$(zipFileName)'  
      
 
- task: AzureCLI@2
  displayName: 'Deploy Code to Function App'
  inputs:
    azureSubscription: 'Ema sub (8a01c013-32ee-4251-b39b-75536d8edf96)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |            
      sasUrl=https://emasplashapp.blob.core.windows.net/app/$(zipFileName)      
      az webapp config appsettings set --resource-group $(resourceGroupName) --name $(functionName) --settings WEBSITE_CONTENTOVERVNET=1
      az webapp config appsettings set --resource-group $(resourceGroupName) --name $(functionName) --settings WEBSITE_RUN_FROM_PACKAGE=$sasUrl
- task: AzureCLI@2
  inputs:
          azureSubscription: 'Ema sub (8a01c013-32ee-4251-b39b-75536d8edf96)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            agent_ip=$(curl -s http://ipinfo.io/ip)
            echo $agent_ip          
            az storage account network-rule remove --resource-group '$(resourceGroupName)' --account-name '$(storageAccountName)' --ip-address $agent_ip      