# Azure DevOps YAML pipeline for deploying an Azure Function app with private endpoint enabled
 
trigger:
  branches:
    include:
    - main
 
variables:
  # Azure Function app settings
  functionName: "test-private-endpoint-ema"
  resourceGroupName: "DefaultResourceGroup-WEU"
   
  # Azure Storage account settings
  storageAccountName: "emasplashapp"
  storageAccountKey: "bMWohgvScWZPEh3pOTYKC886UpHW1q0PUqKYmkD7AmDTEVb/4L1X93hpD3Eq3t3xYhjGTugZW91R+AStC8e3ww=="
  containerName: "app"
  zipFileName: "test-endpoint.zip"
   
  # Deployment package settings
  sourceDirectory: "$(System.DefaultWorkingDirectory)"
  zipFile: "$(System.DefaultWorkingDirectory)/test-endpoint.zip"
   
steps:
- task: ArchiveFiles@2
  displayName: 'Build Deployment Package'
  inputs:
    rootFolderOrFile: '$(sourceDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(zipFile)'

- task: AzureCLI@2
  inputs:
      azureSubscription: 'Ema sub (8a01c013-32ee-4251-b39b-75536d8edf96)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az storage blob upload --overwrite --account-name '$(storageAccountName)' --account-key '$(storageAccountKey)' --container-name 'app' --file '$(zipFile)' --name '$(zipFileName)'
  
 
- task: AzureCLI@2  
  inputs:
    scriptType: 'bash'
    azureSubscription: 'Ema sub (8a01c013-32ee-4251-b39b-75536d8edf96)'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Set the storage account name and key
      storageAccountName='$(storageAccountName)'
      storageAccountKey='$(storageAccountKey)'
      
      # Set the container name and file path
      containerName='$(containerName)'
      filePath="test-endpoint.zip"
      
      # Set the expiry time for the SAS token (in minutes)
      expiryTimeInMinutes="60"
      
    
      
      # Generate the SAS token for the file
      sasToken=$(az storage blob generate-sas --account-name $storageAccountName --account-key $storageAccountKey --container-name $containerName --name $filePath --expiry 2023-04-28T00:00:00Z --permissions r)
      
      echo $sasToken

      # Output the SAS token
      echo "##vso[task.setvariable variable=sasToken]$sasToken"
      
 
- task: AzureCLI@2
  displayName: 'Deploy Code to Function App'
  inputs:
    azureSubscription: 'Ema sub (8a01c013-32ee-4251-b39b-75536d8edf96)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $sasUrl = 'https://emasplashapp.blob.core.windows.net/app/test-endpoint.zip?$(sasToken)'
      az config set extension.use_dynamic_install=yes_without_prompt
      az functionapp deployment source config-zip `
          --resource-group $(resourceGroupName) `
          --name $(functionName) `
          --src "$sasUrl"
