# Azure DevOps YAML pipeline for deploying an Azure Function app with private endpoint enabled
 
trigger:
  branches:
    include:
    - main
 
variables:
  # Azure Function app settings
  functionName: "test-private-endpoint-ema"
  resourceGroupName: "DefaultResourceGroup-WEU"
   
  # Azure Storage account settings
  storageAccountName: "emasplashapp"
  storageAccountKey: "bMWohgvScWZPEh3pOTYKC886UpHW1q0PUqKYmkD7AmDTEVb/4L1X93hpD3Eq3t3xYhjGTugZW91R+AStC8e3ww=="
  containerName: "app"
  zipFileName: "test-endpoint.zip"
   
  # Deployment package settings
  sourceDirectory: "$(System.DefaultWorkingDirectory)"
  zipFile: "$(System.DefaultWorkingDirectory)/test-endpoint.zip"
   
steps:
- task: ArchiveFiles@2
  displayName: 'Build Deployment Package'
  inputs:
    rootFolderOrFile: '$(sourceDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(zipFile)'
 
- task: AzureCLI@2
  displayName: 'Generate SAS URL'
  inputs:
    azureSubscription: 'Ema sub (8a01c013-32ee-4251-b39b-75536d8edf96)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $sasToken = (New-AzStorageContainerSASToken -Context $(New-AzStorageContext -StorageAccountName $(storageAccountName) -StorageAccountKey $(storageAccountKey)) -ExpiryTime (Get-Date).AddDays(1) -FullUri -Name $(containerName) -Permission r -Protocol HttpsOnly)
      Write-Host "##vso[task.setvariable variable=SAS_URL]$sasToken/$(zipFileName)"
 
- task: AzureCLI@2
  displayName: 'Deploy Code to Function App'
  inputs:
    azureSubscription: 'Ema sub (8a01c013-32ee-4251-b39b-75536d8edf96)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $sasUrl = $(SAS_URL)
      az functionapp deployment source config-zip `
          --resource-group $(resourceGroupName) `
          --name $(functionName) `
          --package-url $sasUrl `
          --src-url "$sasUrl/$(zipFileName)"
