# Azure DevOps YAML pipeline for deploying an Azure Function app with private endpoint enabled
 
trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest
 
variables:
  # Azure Function app settings
  functionName: "test-private-endpoint-ema"
  resourceGroupName: "DefaultResourceGroup-WEU"
   
  # Azure Storage account settings
  storageAccountName: "emasplashapp"
  storageAccountKey: "bMWohgvScWZPEh3pOTYKC886UpHW1q0PUqKYmkD7AmDTEVb/4L1X93hpD3Eq3t3xYhjGTugZW91R+AStC8e3ww=="
  containerName: "app"
  zipFileName: "test-endpoint-v9.zip"
   
  # Deployment package settings
  sourceDirectory: "$(System.DefaultWorkingDirectory)"
  zipFile: "$(System.DefaultWorkingDirectory)/test-endpoint-v9.zip"
   
steps:
- task: ArchiveFiles@2
  displayName: 'Build Deployment Package'
  inputs:
    rootFolderOrFile: '$(sourceDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(zipFile)'

- task: AzureCLI@2
  inputs:
      azureSubscription: 'Ema sub (8a01c013-32ee-4251-b39b-75536d8edf96)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        agent_ip=$(echo $AGENT_IPADDRESS)
        az storage account network-rule add --resource-group '$(resourceGroupName)' --account-name '$(storageAccountName)' --ip-address $agent_ip
        az storage blob upload --overwrite --account-name '$(storageAccountName)' --account-key '$(storageAccountKey)' --container-name 'app' --file '$(zipFile)' --name '$(zipFileName)'
        az storage account network-rule remove --resource-group '$(resourceGroupName)' --account-name '$(storageAccountName)' --ip-address $agent_ip

        
- task: AzureCLI@2  
  inputs:
    scriptType: 'bash'
    azureSubscription: 'Ema sub (8a01c013-32ee-4251-b39b-75536d8edf96)'
    scriptLocation: 'inlineScript'
    inlineScript: |    
      # Set the storage account name and key
      storageAccountName='$(storageAccountName)'
      storageAccountKey='$(storageAccountKey)'
      
      # Set the container name and file path
      containerName='$(containerName)'
      filePath='$(zipFileName)'
      
      # Set the expiry time for the SAS token (in minutes)
      expiryTimeInMinutes="60"
      
      # Generate the SAS token for the file
      sasToken=$(az storage blob generate-sas --account-name $storageAccountName --account-key $storageAccountKey --container-name $containerName --name $filePath --expiry 2024-04-28T00:00:00Z --permissions r)      
      
      echo $sasToken

      # Output the SAS token
      echo "##vso[task.setvariable variable=sasToken]$sasToken"
      
 
- task: AzureCLI@2
  displayName: 'Deploy Code to Function App'
  inputs:
    azureSubscription: 'Ema sub (8a01c013-32ee-4251-b39b-75536d8edf96)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |      
      #ENCODED_SAS_TOKEN=$(python -c "import sys, urllib.parse; print(urllib.parse.quote(sys.argv[1]))" "$(sasToken)")
      #sasUrl=https://emasplashapp.blob.core.windows.net/app/$(zipFileName)?$(sasToken)
      sasUrl=https://emasplashapp.blob.core.windows.net/app/$(zipFileName)
      echo $sasUrl
      az webapp config appsettings set --resource-group $(resourceGroupName) --name $(functionName) --settings WEBSITE_CONTENTOVERVNET=1
      az webapp config appsettings set --resource-group $(resourceGroupName) --name $(functionName) --settings WEBSITE_RUN_FROM_PACKAGE=$sasUrl      
      # az storage blob download -f '$(zipFile)' -c '$(containerName)' -n '$(zipFileName)' --sas-token '$(sasToken)' --account-name '$(storageAccountName)'
      # az functionapp deployment source config-zip -g $resourceGroup -n $functionAppName --src $packageUri --build-remote false --slot staging
      #az config set extension.use_dynamic_install=yes_without_prompt
      #az functionapp deployment source config-zip --resource-group $(resourceGroupName) --name $(functionName) --src $sasUrl 

      # az webapp config appsettings set --resource-group DefaultResourceGroup-WEU --name test-private-endpoint-ema --settings WEBSITE_RUN_FROM_PACKAGE=https://emasplashapp.blob.core.windows.net/app/test-endpoint.zip?se=2024-04-28T00%3A00%3A00Z&sp=r&sv=2021-06-08&sr=b&sig=WHTLp6TfPRo0kZP%2Fmr%2BoA8XK8V1dCA23dqqcFX1SkRk%3D
    